name: CI -> Deploy to AUR

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          ls -lha .
          echo "github.repository: ${{ github.repository }}"
          echo "github: ${{ github }}"
          echo "github.event: ${{ github.event }}"
          echo "github.event_path: ${{ github.event_path }}"
          echo "github.workflow: ${{ github.workflow }}"
          echo "github.job: ${{ github.job }}"
          echo "github.run_id: ${{ github.run_id }}"
          echo "github.run_number: ${{ github.run_number }}"
          echo "github.repository: ${{ github.repository }}"
          echo "github.repository_owner: ${{ github.repository_owner }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.sha: ${{ github.sha }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.token: ${{ github.token }}"
          echo "github.workspace: ${{ github.workspace }}"
          echo "github.action: ${{ github.action }}"
          echo "github.action_path: ${{ github.action_path }}"
          ls -lha "${{ github.repository }}"
