name: CI -> Deploy to AUR

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          ls -lha .
#        echo ${{ github }}
#        echo ${{ github.event }}
#        echo ${{ github.event_path }}
#        echo ${{ github.workflow }}
#        echo ${{ github.job }}
#        echo ${{ github.run_id }}
#        echo ${{ github.run_number }}
#        echo ${{ github.repository }}
#        echo ${{ github.repository_owner }}
#        echo ${{ github.event_name }}
#        echo ${{ github.sha }}
#        echo ${{ github.ref }}
#        echo ${{ github.head_ref }}
#        echo ${{ github.token }}
#        echo ${{ github.workspace }}
#        echo ${{ github.action }}
#        echo ${{ github.action_path }}
#        ls -lha ${{ github.repository }}
