name: CI -> Deploy to AUR

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update the AUR package and Commit the changes via Git
        env:
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          WORKSPACE_PATH: ${{ github.workspace }}
        run: |
          # ${{ github.workspace }}/.github/workflows/deployment.sh

      - name: Hello world action step
        uses: ./.github/actions/aur-deployment/
        with:
          who-to-greet: 'Mona the Octant'
