name: CI -> Deploy to AUR

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update the AUR package and Commit the changes via Git
        id: hello
        uses: ./.github/actions/action.yml
        with:
          who-to-greet: 'Mona the Octocat'
        env:
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          WORKSPACE_PATH: ${{ github.workspace }}
        run: |
          echo "Not needs to run this."
      #          ${{ github.workspace }}/.github/workflows/deployment.sh

      - name: Get the output time
          run: echo "The time was ${{ steps.hello.outputs.time }}"
