name: CI -> Deploy to AUR

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          set -xv

          pwd
          ls -lha .

          echo  "../"
          ls -lha ../

          echo  "${HOME}"
          ls -lha "${HOME}"

          mkdir -p "${HOME}/test01"

          echo  "${HOME}"
          ls -lha "${HOME}"

          echo "github.workspace: ${{ github.workspace }}"

          set +xv
