name: CI -> Deploy to AUR

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update the AUR package and Commit the changes via Git
        env:
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          WORKSPACE_PATH: ${{ github.workspace }}
        run: |
          echo Not needs to run this
          ls -lha /home/runner/work/linux-battery-discharging-beep/
          ls -lha /home/runner/work/linux-battery-discharging-beep/linux-battery-discharging-beep/
          ls -lha /home/runner/work/linux-battery-discharging-beep/linux-battery-discharging-beep/.git/
          ls -lha /home/runner/work/linux-battery-discharging-beep/linux-battery-discharging-beep/.git/actions/
          # ${{ github.workspace }}/.github/workflows/deployment.sh

      - name: Hello world action step
        uses: ./.git/actions/
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
